config/routes.rb
Rails.application.routes.draw do
  root 'public#index'

  get 'show/:permalink', :to => 'public#show', :as => 'public_show'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :admin_users, except: :show do
    member do
      get :delete
    end
  end
  
  resources :subjects do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  get 'test/index'
  get 'test/cheese'

  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/google'

  # default route
  # get ':controller(/:action(:id))'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/section.rb
class Section < ApplicationRecord

    acts_as_list :scope => :page

    scope :sorted, lambda {order("position ASC")}
    scope :visible, lambda {where(visible: true)}

    belongs_to :page
    has_many :section_edits
    has_many :admin_users, :through => :section_edits

    CONTENT_TYPES = ['text', 'HTML']

    validates_presence_of :name
    validates_length_of :name, :maximum => 255
    validates_inclusion_of :content_type, :in => CONTENT_TYPES,
        :message => "must be one of #{CONTENT_TYPES.join(', ')}"
    validates_presence_of :content

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  layout 'admin'

  before_action :confirm_logged_in
  before_action :find_page
  before_action :set_section_count, :only => [:new, :create, :edit, :update]

  
  def index
    @sections  = @page.sections.sorted
  end

  def show
    @section = Section.find(params[:id])
  end

  def new
    @section = Section.new(page_id: @page.id)
  end

  def create
    @section = Section.new(section_params)
    @section.page = @page

    if @section.save
      flash[:notice] = 'Section created successfully.'
      redirect_to(sections_path(page_id: @page.id))
    else
      puts @section.errors
      flash[:error] = "Error: #{@section.errors.full_messages}"
      render('new')
    end
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])
    if @section.update(section_params)
      flash[:notice] = 'Section updated successfully.'
      redirect_to(section_path(@section, page_id: @page.id))
    else
      render('edit')
    end
  end

  def delete
    @section = Section.find(params[:id])
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    flash[:notice] = "Section #{@section.name} deleted successfully."
    redirect_to(sections_path(page_id: @page.id))
  end

  private

  def section_params
    params.require(:section).permit(:name, :position, :visible, :content_type, :content)
  end

  def find_page
    @page =Page.find(params[:page_id])
  end

  def set_section_count
    @section_count = @page.sections.count
    if params[:action] == 'new' || params[:action] == 'create'
      @section_count += 1
    end
  end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Section form fields">
    <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
    </tr>
    <tr>
        <th>Page</th>
        <td><%= f.object.page.name %></td>
    </tr>
    <tr>
        <th>Position</th>
        <td><%= f.select(:position, 1..@section_count) %></td>
    </tr>
    <tr>
        <th>Visible</th>
        <td><%= f.check_box(:visible) %></td>
    </tr>
    <tr>
        <th>Content Type</th>
        <td>
            <%= f.radio_button(:content_type, 'text') %> Text 
            <%= f.radio_button(:content_type, 'HTML') %> HTML
        </td>
    </tr>
    <tr>
        <th>Content</th>
        <td><%= f.text_area(:content, :size => '40x10') %></td>
    </tr>
</table>

app/views/sections/delete.html.erb
<%= link_to("<< Back to List", sections_path(page_id: @page.id), :class => 'back-link') %>

<div class="sections delete">
  <h2>Delete Section</h2>

  <%= form_for(@section, :url => section_path(@section, page_id: @page.id), :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this section?</p>

    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Section") %>
    </div>

  <% end %>
</div>

app/views/sections/edit.html.erb
<%= link_to("<< Back to List", sections_path(page_id: @page.id), :class => 'back-link') %>

<div class="sections new">
  <h2>Update Section</h2>

  <%= form_for(@section, url: section_path(@section, page_id: @page.id)) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Section") %>
    </div>

  <% end %>
</div>

app/views/sections/index.html.erb
<% @page_title = 'All Sections' %>

<%= link_to  "<< Back to Pages", pages_path(subject_id: @page.subject_id), :class => 'back-link' %>

<div class="sections index">
  <h2>Sections</h2>

  <%= link_to("Add New section", new_section_path(page_id: @page.id), :class => 'action new') %>

  <table class="listing" summary="section list">
    <tr class="header">
      <th>#</th>
      <th>Section</th>
      <th>Page #</th>
      <th>Visible</th>
      <th>Content Type</th>
      <th>Actions</th>
    </tr>
    <% @sections.each do |section| %>
    <tr>
      <td><%= section.position %></td>
      <td><%= section.name %></td>
      <td><%= section.page_id %></td>
      <td class="center"><%= status_tag(section.visible) %></td>
      <td class="center"><%= section.content_type %></td>
      <td class="actions">
        <%= link_to("Show", section_path(section, page_id: @page.id), :class => 'action show') %>
        <%= link_to("Edit", edit_section_path(section, page_id: @page.id), :class => 'action edit') %>
        <%= link_to("Delete", delete_section_path(section, page_id: @page.id), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/sections/new.html.erb
<% if !flash[:error].blank? %>
  <div class="error">
    <%= flash[:error] %>
  </div>
<% end %>


<%= link_to("<< Back to List", sections_path(page_id: @page.id), :class => 'back-link') %>

<div class="sections new">
  <h2>Create Section</h2>

  <%= form_for(@section, url: sections_path(page_id: @page.id)) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Section") %>
    </div>

  <% end %>
</div>

app/views/sections/show.html.erb
<%= link_to("<< Back to List", sections_path(page_id: @page.id), :class => 'back-link') %>

<div class="sections new">
  <h2>View Section</h2>
    <table summary="Section form fields">
      <tr>
        <th>Name</th>
        <td><%= @section.name %></td>
      </tr>
      <tr>
        <th>Page #</th>
        <td><%= @section.page_id %></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%= @section.position %></td>
      </tr>
      <tr>
        <th>Visible</th>
        <td><%= @section.visible %></td>
      </tr>
      <tr>
        <th>Content Type</th>
        <td><%= @section.content_type %></td>
      </tr>
      <tr>
        <th>Content</th>
        <td><%= @section.content %></td>
      </tr>
    </table>
</div>