config/routes.rb
Rails.application.routes.draw do
  root 'public#index'

  get 'show/:permalink', :to => 'public#show', :as => 'public_show'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :admin_users, except: :show do
    member do
      get :delete
    end
  end
  
  resources :subjects do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  get 'test/index'
  get 'test/cheese'

  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/google'

  # default route
  # get ':controller(/:action(:id))'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

    has_secure_password

    scope :sorted, lambda {order("name ASC")}

    has_and_belongs_to_many :pages
    has_many :section_edits
    has_many :sections, :through => :section_edits

    EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\z/i
    FORBIDDEN_USER_NAME = ['I am not allowed', 'Pancake']

    validates :name, :presence => true,
        :length => {:maximum => 75}
    
    validates :username, :presence => true,
        :length => {:within => 8..25},
        :uniqueness => true

    validates :email, :presence => true,
        :length => {:maximum => 100},
        :format => {:with => EMAIL_REGEX},
        :confirmation => true

    validate :username_is_allowed

    private 

    def username_is_allowed
        if FORBIDDEN_USER_NAME.include?(username)
            errors.add(
                :username, 
                "cannot be: '#{FORBIDDEN_USER_NAME.join('\' or \'')}'."
            )
        end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
    
    acts_as_list :scope => :subject

    scope :sorted, lambda {order("position ASC")}
    scope :visible, lambda {where(visible: true)}
    
    has_and_belongs_to_many :admin_users
    belongs_to :subject, :optional => true
    has_many :sections

    validates_presence_of :name
    validates_length_of :name, :maximum => 255
    validates_presence_of :permalink
    validates_length_of :permalink, :within => 3..255
    validates_uniqueness_of :permalink

end

app/models/section.rb
class Section < ApplicationRecord

    acts_as_list :scope => :page

    scope :sorted, lambda {order("position ASC")}
    scope :visible, lambda {where(visible: true)}

    belongs_to :page
    has_many :section_edits
    has_many :admin_users, :through => :section_edits

    CONTENT_TYPES = ['text', 'HTML']

    validates_presence_of :name
    validates_length_of :name, :maximum => 255
    validates_inclusion_of :content_type, :in => CONTENT_TYPES,
        :message => "must be one of #{CONTENT_TYPES.join(', ')}"
    validates_presence_of :content

end

app/models/section_edit.rb
class SectionEdit < ApplicationRecord

    belongs_to :admin_user
    belongs_to :section

end

app/models/subject.rb
class Subject < ApplicationRecord

    acts_as_list
    has_many :pages

    scope :visible, lambda {where(:visible => true)}
    scope :invisible, lambda {where(:visible => false)}
    scope :sorted, lambda {order("position ASC")}
    scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"])}

    validates_presence_of :name
    validates_length_of :name, :maximum => 255
    

end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  layout 'admin'

  before_action :confirm_logged_in, except: [:login, :attempt_login, :logout]

  def menu
    #displays text and links
    @username = session[:username]
  end

  def login
    #login form
  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = AdminUser.where(:username => params[:username]).first
      
      if found_user 
        authorized_user = found_user.authenticate(params[:password])
      end
    end

    if authorized_user 
      session[:user_id] = authorized_user.id
      session[:username] = authorized_user.username
      flash[:notice] = "You are now logged in!"
      redirect_to(admin_path)
    else
      flash.now[:notice] = "Invalid username/password combination."
      render('login')
    end
  end

  def logout
    session[:user_id] = nil
    session[:username] = nil
    flash[:notice] = "Logged out"

    redirect_to(access_login_path)
  end
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  layout false

  def index
    render('index') # this is the default action
  end

  # note if this doesn't exist, 
  # then it seems to just return the default associated view
  def hello
    @id = params[:id]
    @page = params[:page]
    
    @name = ['Bob', 'Me', 'Hello', 'Blarg'].shuffle[0]
  end

  def other_hello
    #redirect_to(:controller => 'demo', :action => 'hello')
    redirect_to(:action => 'hello') # seems to be a 302 redirect
  end

  def google
    # seems the https portion is needed to indentify it as hardcoded
    redirect_to('https://www.google.com')
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  layout 'admin'

  before_action :confirm_logged_in
  before_action :find_subject
  before_action :set_page_count, :only => [:new, :create, :edit, :update]
  before_action :find_page_by_id, :only => [:show, :edit, :update, :delete, :destroy]
  
  def index
    @pages = @subject.pages.sorted
  end

  def show

  end

  def new
    @page = Page.new(subject_id: @subject.id)
  end

  def create
    @page = Page.new(page_params)
    @page.subject = @subject

    if @page.save
      flash[:notice] = 'Page created successfully.'
      redirect_to(pages_path(subject_id: @subject.id))
    else
      puts @page.errors
      flash[:error] = "Error: #{@page.errors.full_messages}"
      render('new')
    end
  end

  def edit

  end

  def update
    if @page.update(page_params)
      flash[:notice] = 'Page updated successfully.'
      redirect_to(page_path(@page, subject_id: @subject.id))
    else
      render('edit')
    end
  end

  def delete

  end

  def destroy
    @page.destroy
    flash[:notice] = "Page #{@page.name} deleted successfully."
    redirect_to(pages_path(subject_id: @subject.id))
  end

  private

  def page_params
    params.require(:page).permit(:name, :position, :visible, :permalink)
  end

  def find_page_by_id
    @page = Page.find(params[:id])
  end

  def find_subject
    @subject = Subject.find(params[:subject_id])
  end

  def set_page_count
    @page_count = @subject.pages.count
    if params[:action] == 'new' || params[:action] == 'create'
      @page_count += 1
    end
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController

  layout 'public'

  before_action :setup_navigation

  def index
    #intro text
  end

  def show
    @page = Page.visible.where(:permalink => params[:permalink]).first
    if @page.nil?
      redirect_to(root_path)
    end
    #show for show.html.erb
  end

  private 

  def setup_navigation
    @subjects = Subject.visible.sorted
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  layout false 

  def index
  end

  def cheese
  end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/admin_user_helper.rb
module AdminUserHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

    def error_messages_for(object)
        render(
            :partial => 'application/error_messages',
            :locals => {:object => object}
        )
    end

    def status_tag(boolean, options={})
        options[:true_text] ||= ''
        options[:false_text] ||= ''

        if boolean
            content_tag(:span, options[:true_text], :class => 'status true')
        else
            content_tag(:span, options[:false_text], :class => 'status false')
        end
    end
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/layouts/_navigation.html.erb
<% subjects ||= [] %>
<ul>
    <% subjects.each do |subject| %>
    <li>
        <%= subject.name %>
        <ul>
            <% subject.pages.visible.sorted.each do |page| %>
            <li><%= link_to_unless_current(page.name, public_show_path(page.permalink)) %></li>
            <% end %>
        </ul>
    </li>
    <% end %>
</ul>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Simple CMS: <%= @page_title || "Admin Area" %></title>

        <%= stylesheet_link_tag('admin', :media => 'all') %>
        <%= javascript_pack_tag('application') %>
    </head>

    <body>
        <header id="header">
            <h1>Simple CMS Admin</h1>
        </header>

        <main id="main">
            <% if !flash[:notice].blank? %>
                <div class="notice">
                    <%= flash[:notice] %>
                </div>
            <% end %>

            <div id="content">
                    <%= yield %>
            </div>

        </main>

        <footer id="footer">
            <p id="copyright">
                &copy; cheese.com
            </p>
        </footer>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Temp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag('application', :media => 'all') %>
    <%= javascript_pack_tag('application') %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Simple CMS <%= " | #{@page_title}" if @page_title %></title>

        <%= stylesheet_link_tag('application', :media => 'all') %>
        <%= javascript_pack_tag('application') %>
    </head>

    <body>
        <header id="header">
            <h1>Simple CMS</h1>
        </header>

        <main id="main">

            <div id="navigation">
                <%= render partial: 'layouts/navigation', locals: {subjects: @subjects} %>  
            </div>
            
            <div id="content">
                    <%= yield %>
            </div>

            <div class="clear"></div>
        </main>

        <footer id="footer">
            <p id="copyright">
                &copy; cheese.com
            </p>
        </footer>
    </body>
</html>

app/views/pages/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Page form fields">
    <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
    </tr>
    <tr>
        <th>Subject</th>
        <td><%= f.object.subject.name %></td>
    </tr>
    <tr>
        <th>Permalink</th>
        <td><%= f.text_field(:permalink) %></td>
    </tr>
    <tr>
        <th>Position</th>
        <td><%= f.select(:position, 1..@page_count) %></td>
    </tr>
    <tr>
        <th>Visible</th>
        <td><%= f.check_box(:visible) %></td>
    </tr>
</table>

app/views/pages/delete.html.erb
<%= link_to("<< Back to List", pages_path(subject_id: @subject.id), :class => 'back-link') %>

<div class="pages delete">
  <h2>Delete Page</h2>

  <%= form_for(@page, :method => 'delete', :url => page_path(@page, subject_id: @subject.id)) do |f| %>

    <p>Are you sure you want to permanently delete this page?</p>

    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Page") %>
    </div>

  <% end %>
</div>

app/views/pages/edit.html.erb
<%= link_to("<< Back to List", pages_path(subject_id: @subject.id), :class => 'back-link') %>

<div class="pages new">
  <h2>Update Page</h2>

  <%= form_for(@page, url: page_path(@page, subject_id: @subject.id)) do |f| %>
    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Page") %>
    </div>

  <% end %>
</div>

app/views/pages/index.html.erb
<% @page_title = 'All Pages' %>

<%= link_to("<< Back to Subjects", subjects_path, :class => 'back-link') %>

<div class="pages index">
  <h2>Pages</h2>

  <%= link_to("Add New Page", new_page_path(subject_id: @subject.id), :class => 'action new') %>

  <table class="listing" summary="page list">
    <tr class="header">
      <th>#</th>
      <th>Name</th>
      <th>Subject #</th>
      <th>Visible</th>
      <th>Actions</th>
    </tr>
    <% @pages.each do |page| %>
    <tr>
      <td><%= page.position %></td>
      <td><%= page.name %></td>
      <td><%= page.subject_id %></td>
      <td class="center"><%= status_tag(page.visible) %></td>
      <td class="actions">
        <%= link_to("View Sections",sections_path(page_id: page.id), :class => 'action show') %>
        <%= link_to("Show", page_path(page, subject_id: @subject.id), :class => 'action show') %>
        <%= link_to("Edit", edit_page_path(page, subject_id: @subject.id), :class => 'action edit') %>
        <%= link_to("Delete", delete_page_path(page, subject_id: @subject.id), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/pages/new.html.erb
<%= link_to("<< Back to List", pages_path(subject_id: @subject.id), :class => 'back-link') %>

<div class="pages new">
  <h2>Create Page</h2>

  <%= form_for(@page, url: pages_path(subject_id: @subject.id)) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Page") %>
    </div>

  <% end %>
</div>

app/views/pages/show.html.erb
<%= link_to("<< Back to List", pages_path(subject_id: @subject.id), :class => 'back-link') %>

<div class="pages show">
  <h2>Show Page</h2>

  <table summary="page detail view">
    <tr>
      <th>Name</th>
      <td><%= @page.name %></td>
    </tr>
    <tr>
      <th>Subject #</th>
      <td><%= @page.subject_id %></td>
    </tr>
    <tr>
      <th>Permalink</th>
      <td><%= @page.permalink %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @page.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @page.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @page.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @page.updated_at %></td>
    </tr>
  </table>

</div>